import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Footer from '../src/components/Footer'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span style={{color:'lightblue'}}>sample page</span>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div style={{width:'100%',display:'flex',}}>
          <Link href={'/with-useEffect'}>
            <a style={{margin:'0 4px',width:'calc(100% / 2 - 8px)',border:'1px solid gray',textAlign:'center',borderRadius:'10px'}}>
              <p>with useEffect page</p>
            </a>
          </Link>
          <Link href={'/with-react-query'}>
            <a style={{margin:'0 4px',width:'calc(100% / 2 - 8px)',border:'1px solid gray',textAlign:'center',borderRadius:'10px'}}>
              <p>with reactQuery page</p>
            </a>
          </Link>
        </div>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
